### ISSUE TITLE
GateMateA1-EVB_Rev_A.pdf still shows R5=1.3 Ohms

### ISSUE THREAD

**Issue by Andy2No** [OLIMEX/GateMateA1-EVB#4]
In the schematic in PDF form, GateMateA1-EVB_Rev_A.pdf https://github.com/OLIMEX/GateMateA1-EVB/blob/main/HARDWARE/GateMateA1-EVB-Rev.A/GateMateA1-EVB_Rev_A.pdf, the value of R5 is still shown as 1.3 Ohms, despite that having to be revised to 22 Ohms to reduce PLL voltage ripple, as noted in IMPORTANT-NOTE.txt https://github.com/OLIMEX/GateMateA1-EVB/blob/main/HARDWARE/GateMateA1-EVB-Rev.A/IMPORTANT-NOTE.txt

There doesn't appear to be an updated version of that PDF, with the correct value.

**Comment by TsvetanUsunov** [comment]
Thanks for pointing this out. 
The 22 ohm is not good value either.
Our people forgot to update the board revision Rev.B changes which we ship now
I just updated it. The correct value for R5 is 4.7 ohm
